import type { Metadata } from "next";
import { Lato } from "next/font/google";

import "./globals.scss";
import NavBar from "@/components/Navbar";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  display: "swap",
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`rootlayout ${lato.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
